#services:
##  db:
##    image: postgres:16
##    container_name: bankcards-db
##    ports:
##      - "5434:5432"
##    environment:
##      POSTGRES_USER: postgres
##      POSTGRES_PASSWORD: postgres
##      POSTGRES_DB: bankcards
##    healthcheck:
##      test: ["CMD-SHELL", "pg_isready -U postgres"]
##      interval: 5s
##      timeout: 5s
##      retries: 10
##
##
##volumes:
##  postgres_data: {}  # ← исправленное имя

services:
  db:
    image: postgres:16
    container_name: bankcards-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres