spring:
  application:
    name: bankcards
  datasource:
    url: jdbc:postgresql://localhost:5432/bankcards
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:db/migration/changelog/db.changelog-master.yaml
  security:
    jwt:
      secret: MTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTI=  # "12345678901234567890123456789012" в base64
      expiration: 86400000  # 24 часа

encryption:
  secret-key: "dGVzdC1zZWNyZXQta2V5LTI1Ni1iaXRzLTEyMzQ1Njc=" # test-secret-key-256-bits-1234567

server:
  port: 8080
business:
  rules:
    min-card-balance: 0.00 # Минимальный баланс карты (не может быть отрицательным)
    max-transfer-amount: 1000000.00 # Максимальная сумма перевода за одну операцию
    min-transfer-amount: 0.01 # Минимальная сумма перевода
    max-cards-per-user: 5 # Максимальное количество карт на одного пользователя
    min-initial-balance: 0.00 # Минимальный начальный баланс при создании карты