spring:
  application:
    name: bankcards

  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC

  liquibase:
    enabled: false

  security:
    jwt:
      secret: MTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTI=
      expiration: 86400000
  springdoc:
    packages-to-scan: ru.effectivemobile.bankcards.controller
    paths-to-exclude: /error, /actuator/**
    swagger-ui:
      path: /swagger-ui.html
      disable-swagger-default-url: true

logging:
  level:
    org.springframework: INFO
    com.zaxxer.hikari: DEBUG
    io.swagger.v3: DEBUG
    org.springdoc: DEBUG

encryption:
  secret-key: "dGVzdC1zZWNyZXQta2V5LTI1Ni1iaXRzLTEyMzQ1Njc="

server:
  port: 8082

business:
  rules:
    min-card-balance: 0.00
    max-transfer-amount: 1000000.00
    min-transfer-amount: 0.01
    max-cards-per-user: 5
    min-initial-balance: 0.00